language: python
python:
  - "3.7"
  - "3.6"
  - "nightly"
install:
  - "pip install -r requirements.txt"
  - "pip install codecov coverage"
after_script:
  - "codecov"
script:
  - "coverage run tests.py"